### ISSUE TITLE
Links de redes sociais quebrados

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/uffs.cc#1]
**Descreva o bug/problema**
Os links de rodapé para instagram, facebook, twitter e youtube não estão apontando para os perfis corretos.

**Reproduzir**
1. Acesse os links do rodapé do website

**Comment by mateusKoppe** [comment]
Aparentemente abri a issue no repositório de redirecionamento haha, irei recriar a issue no repositório correto caso ninguém tenha reportado lá.

**Comment by Dovyski** [comment]
haha, de fato esse não é o repositório correto. Obrigado pelo aviso. Para os interessados, a discussão continua [aqui](https://github.com/ccuffs/cc.uffs.edu.br/issues/36).
