### ISSUE TITLE
Adicionar encurtador para Grupo de Estudos em NLP

### ISSUE THREAD

**Issue by jeanchilger** [ccuffs/uffs.cc#5]
Seria interessante ter uma URL como `uffs.cc/nlp` que fosse um encurtador para o [site do Grupo de Estudos em NLP](https://uffsnlp.github.io/).

Dei uma olhada no projeto mas (corrija-me se eu estiver enganado) parece que a criação deste encurtador deve ser feito em `/dashboard`, que não aparece disponível em `uffs.cc/dashboard`. Talvez apenas pessoas com acesso ao projeto no servidor possam criar?

**Comment by Dovyski** [comment]
Em um mundo ideal, esse projeto Laravel de encurtar URLs teria todas as funcionalidades do admin para funcionar por conta, mas não é o caso ainda 😁 Por enquanto, os links são criados via SSH.

Criei o link [uffs.cc/nlp](https://uffs.cc/nlp) 🚀

**Comment by jeanchilger** [comment]
Muito obrigado!!!!! Que maravilha ter esse link :smile:. Irei fechar a issue agora.
